#### General tmux config

# Enable clipboard access from within tmux
if -F '#{>=:#{version},3.2}' {
    set -g set-clipboard on
} {
    set -g set-clipboard external
}

# Set terminfo, use 24-bit color if possible
set -g default-terminal "tmux-256color"
if -F '#{>=:#{version},3.2}' {
    set -ag terminal-features '*-256color:RGB:clipboard'
} {
    set -ag terminal-overrides '*-256color:RGB:clipboard'
}

# Update terminal window title dynamically
set -g set-titles on
set -g set-titles-string "#{user}@#h: #W"

# Start window numbers at 1 to match keyboard order with tmux window order
set -g base-index 1
setw -g pane-base-index 1

# Automatically rename windows based on what's running
set -g automatic-rename on

# Renumber windows sequentially after closing any of them
set -g renumber-windows on

# Use the 12h clock
set -g clock-mode-style 12

# Enable focus events
set -g focus-events on

#### Keybindings

set -g prefix C-a
bind Tab select-pane -t :.+
bind BTab select-pane -t :.-
bind C-a last-window

# Open new windows in the same working directory
bind c new-window -c "#{pane_current_path}"
bind C-c new-window -c "#{pane_current_path}"

# Open panes in the same working directory
bind | split-window -h -c "#{pane_current_path}"
bind \\ split-window -fh -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind _ split-window -fv -c "#{pane_current_path}"
bind % split-window -v -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# Swap windows with "<" and ">"
bind -r < swap-window -t -1 \; select-window -t -1
bind -r > swap-window -t +1 \; select-window -t +1

# Resize pane shortcuts
bind -r H resize-pane -L 10
bind -r J resize-pane -D 10
bind -r K resize-pane -U 10
bind -r L resize-pane -R 10

# Reload tmux config
bind r source-file ~/.tmux.conf \; display-message "Sourced ~/.tmux.conf!"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dracula/tmux'

# Dracula
set -g @dracula-plugins "cpu-usage ram-usage"
set -g @dracula-cpu-usage-colors "light_purple dark_gray"
set -g @dracula-ram-usage-colors "green dark_gray"
set -g @dracula-show-flags false
set -g @dracula-left-pad ' '
set -g @dracula-left-icon-padding 0
set -g @dracula-border-contrast true
set -g @dracula-cpu-display-load false

# Don't use powerline gyphs in local TTYs
if-shell 'test -n "$SSH_CONNECTION" || test -n "$DISPLAY" || test -n "$WAYLAND_DISPLAY"' {
    set -g @dracula-show-powerline true
    set -g @dracula-show-left-icon ""
    set -g @dracula-cpu-usage-label ""
    set -g @dracula-ram-usage-label ""
} {
    set -g @dracula-show-powerline false
    set -g @dracula-show-left-icon " "
    set -g @dracula-cpu-usage-label ""
    set -g @dracula-ram-usage-label ""
}

# Solarized Dark Adapted Palette
set -g @dracula-options 'patched'
set -g @dracula-colors "white=#93a1a1
gray=#586e75
dark_gray=#002b36
light_purple=#268bd2
dark_purple=#073642
cyan=#2aa198
green=#859900
orange=#cb4b16
red=#dc322f
pink=#d33682
yellow=#cb4b16"

# Install tmux plugin manager and plugins if not already installed
if '[ ! -d ~/.tmux/plugins/tpm ]' \
   'run-shell "git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins"'

# Initialize tmux plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
