" Kyle's custom vimrc

" Enable Pathogen
silent! execute pathogen#infect()

" General Settings
set nocompatible    " disable compatibility mode
set hidden          " hide buffers when they are abandoned
set autowrite       " automatically save before certain commands
set autochdir       " automatically set current directory to directory of last opened file
set lazyredraw      " do not redraw while executing macros or commands that aren't typed
set nowrap          " don't wrap lines

if has("autocmd")
    " Jump to the last file position when reopening a file
    au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" UI Configuration
if &t_Co >= 256
    if has("termguicolors") && has('nvim')
        set termguicolors
        let g:solarized_termcolors=256
        silent! colorscheme solarized8
    endif

    set number

    " Airline Configuration
    let g:airline_theme='solarized'
    let g:airline_solarized_bg='dark'
endif

set background=dark     " use a dark background
set showmatch           " highlight matching brackets
set noshowmode          " don't show current mode in bottom bar, Airline handles this
set cursorline          " enable current line highlighting (slows down scrolling)

" Spaces and Tabs
set smartindent         " smartly indent based on syntax
set expandtab           " tabs are spaces
set shiftwidth=4        " number of spaces per level of indentation
set softtabstop=4       " number of spaces per tab

" Searching
set hlsearch            " highlight matches
set ignorecase          " do case insensitive matching
set smartcase           " do smart case matching

" NERDTree Configuration
if has("autocmd")
    " Open NERDTree automatically if opening a directory
    autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | endif

    " Close NERDTree if it's the only window left open
    autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
endif

map <C-n> :NERDTreeToggle<CR>
let NERDTreeShowHidden=1
let NERDTreeMinimalUI=1
let NERDTreeDirArrows=1
let NERDTreeAutoDeleteBuffer=1
