" Kyle's custom vimrc

" Enable Pathogen
silent! execute pathogen#infect()

" General Settings
set nocompatible    " disable compatibility mode
set hidden          " hide buffers when they are abandoned
set autowrite       " automatically save before certain commands
set autochdir       " automatically set current directory to directory of last opened file
set lazyredraw      " redraw only when we need to
set ttyfast         " make vim update faster
set autoread        " reload files if they change
set history=1000    " remember a lot of history
set linebreak       " wrap lines at convenient points
set nowrap          " don't wrap lines

" Allow backspace past start of indent
set backspace=indent,eol,start

if has("syntax")
    " Enable syntax highlighting
    syntax on
endif

if has("autocmd")
    " Jump to the last file position when reopening a file
    au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

    " Enable file type identification
    filetype plugin indent on
endif

if has("wildmenu")
    " Enable the wildmenu
    set wildmenu
    set wildmode=longest,list,full
endif

" UI Configuration
colorscheme elflord
if &t_Co >= 256
    " Try to use solarized if term is 256 color
    silent! colorscheme solarized
    set cursorline      " show the cursor line
    set number          " show line numbers

    " Airline Configuration
    let g:airline_theme='solarized'
    let g:airline_solarized_bg='dark'
endif

set background=dark     " use a dark background
set laststatus=2        " always show the status line
set showcmd             " show command in status line
set showmatch           " highlight matching brackets
set noruler             " turn off the ruler
set noshowmode          " show current mode in bottom bar
set display+=lastline   " try to show text that scrolls off the display

" Spaces and Tabs
set expandtab       " tabs are spaces
set shiftwidth=4    " number of spaces per level of indentation
set softtabstop=4   " number of spaces per tab

" Searching
set hlsearch        " highlight matches
set incsearch       " incremental search
set ignorecase      " do case insensitive matching
set smartcase       " do smart case matching

" Start scrolling when we're getting close to margins
set scrolloff=3
set sidescrolloff=5
set sidescroll=1

" Folds
set foldmethod=indent   " Fold based on indent
set foldnestmax=3       " Deepest fold is 3 levels
set nofoldenable        " Don't fold by default

" Plugin-specific Configuration

" NERDTree Configuration
if has("autocmd")
    autocmd StdinReadPre * let s:std_in=1
    autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
    autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | endif
    autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
endif

map <C-n> :NERDTreeToggle<CR>
let NERDTreeShowHidden=1

