" Kyle's customizations
"   http://dougblack.io/words/a-good-vimrc.html
"   https://github.com/amix/vimrc/blob/master/vimrcs/basic.vim

" Pathogen
execute pathogen#infect()

" General
set nocompatible
set hidden          " hide buffers when they are abandoned
set autowrite       " automatically save before certain commands
set autochdir       " automatically set current directory to directory of last opened file
set lazyredraw      " redraw only when we need to
set ttyfast         " make vim faster?

" Colors and Fonts
set background=dark

if &t_Co < 256
    colorscheme default
    set nocursorline
else
    " Use solarized if term is 256 color
    colorscheme solarized
    set cursorline
endif

" Spaces and Tabs
set tabstop=4       " number of spaces per tab
set softtabstop=4   " number of spaces in tab when editing
set expandtab       " tabs are spaces

" UI Config
set number          " show line numbers
set showmatch       " highlight matching [{()}]
set noruler         " turn off the ruler
set noshowmode      " show current mode in bottom bar

" Searching
set hlsearch        " highlight matches
set ignorecase      " do case insensitive matching
set smartcase       " do smart case matching

" NERDTree Config
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
map <C-n> :NERDTreeToggle<CR>

