version: "2.1"
services:
  unifi-controller:
    image: ghcr.io/linuxserver/unifi-controller
    container_name: unifi-controller
    environment:
      - PUID=115
      - PGID=121
      - MEM_LIMIT=256M
    volumes:
      - /opt/appdata/unifi-controller:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 127.0.0.1:8443:8443
      - 1900:1900/udp
    restart: unless-stopped
  kanzi:
    image: ghcr.io/linuxserver/kanzi
    container_name: kanzi
    environment:
      - PUID=119
      - PGID=123
      - TZ=America/Chicago
      - INVOCATION_NAME=kodi
      - URL_ENDPOINT=https://kanzi.tacomafia.net
    volumes:
      - /opt/appdata/kanzi:/config
    ports:
      - 127.0.0.1:8000:8000
    restart: unless-stopped
  flexget:
    image: wiserain/flexget
    container_name: flexget
    environment:
      - PUID=114
      - PGID=124
      - TZ=America/Chicago
      - FG_LOG_LEVEL=info
    volumes:
      - /opt/appdata/flexget:/config
      - /srv/shared/video/Series:/srv/shared/video/Series:ro
    restart: unless-stopped
  freshrss:
    image: ghcr.io/linuxserver/freshrss
    container_name: freshrss
    environment:
      - PUID=120
      - PGID=125
      - TZ=America/Chicago
    volumes:
      - /opt/appdata/freshrss:/config
    ports:
      - 127.0.0.1:8001:80
    restart: unless-stopped
  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
      - UMASK_SET=022
      - DELUGE_LOGLEVEL=warning
    volumes:
      - /opt/appdata/deluge:/config
      - /var/working:/var/working
      - /srv/shared/torrents:/srv/shared/torrents
    restart: unless-stopped
  fulltextrss:
    image: heussd/fivefilters-full-text-rss
    container_name: fulltextrss
    volumes:
      - /var/www/html/cache
      - /opt/appdata/fulltextrss/ftr-site-config:/var/www/html/site_config/standard:ro
      - /opt/appdata/fulltextrss/custom_config.php:/var/www/html/custom_config.php:ro
      - /opt/appdata/fulltextrss/mpm_prefork.conf:/etc/apache2/mods-enabled/mpm_prefork.conf:ro
    ports:
      - 127.0.0.1:8002:80
    restart: unless-stopped
  grocy:
    image: ghcr.io/linuxserver/grocy
    container_name: grocy
    environment:
      - PUID=121
      - PGID=126
      - TZ=America/Chicago
    volumes:
      - /opt/appdata/grocy:/config
    ports:
      - 127.0.0.1:8003:80
    restart: unless-stopped
  doh-server:
    image: satishweb/doh-server
    container_name: doh-server
    environment:
      DEBUG: "0"
      UPSTREAM_DNS_SERVER: "udp:192.168.1.30:53"
      DOH_HTTP_PREFIX: "/q"
      DOH_SERVER_LISTEN: ":8053"
    ports:
      - 127.0.0.1:8053:8053
    restart: unless-stopped
