version: "3.9"
services:
  adguard:
    image: docker.io/adguard/adguardhome:latest
    container_name: adguard
    network_mode: "host"
    environment:
      - TZ=America/Chicago
    volumes:
      - /opt/appdata/adguard/work:/opt/adguardhome/work
      - /opt/appdata/adguard/conf:/opt/adguardhome/conf
    restart: unless-stopped
  cloudflare-ddns:
    image: ghcr.io/joshuaavalon/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    network_mode: "host"
    environment:
      - PUID=114
      - PGID=120
      - TZ=America/Chicago
      - CRON=0 */6 * * *
    volumes:
      - /opt/appdata/cloudflare-ddns/config.yaml:/app/config.yaml
    restart: unless-stopped
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    network_mode: "host"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
# Must use "host" network_mode as Docker interferes with iptables firewall
#networks:
#  default:
#    ipam:
#      config:
#        - subnet: 172.17.0.0/16
