services:
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller
    container_name: unifi-controller
    network_mode: "host"
    environment:
      - PUID=113
      - PGID=119
      - MEM_LIMIT=512M
      - MEM_STARTUP=512M
    volumes:
      - /opt/appdata/unifi-controller:/config
    restart: unless-stopped
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: "host"
    environment:
      TZ: 'America/Chicago'
      ServerIP: '192.168.1.1'
      ServerIPv6: 'fd06:4f9a:934d:1::1'
      VIRTUAL_HOST: 'pihole.tacomafia.net'
      WEB_PORT: '8000'
    volumes:
      - /opt/appdata/pihole/etc/pihole/:/etc/pihole/
      - /opt/appdata/pihole/etc/dnsmasq.d/:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
  cloudflare-ddns:
    image: ghcr.io/joshuaavalon/cloudflare-ddns
    container_name: cloudflare-ddns
    network_mode: "host"
    environment:
      PUID: "114"
      PGID: "120"
      CRON: "*/60 * * * *"
    volumes:
      - /opt/appdata/cloudflare-ddns/config.yaml:/app/config.yaml
    restart: unless-stopped
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: gateway
    ports:
      - "19999:19999"
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /opt/appdata/netdata/config:/etc/netdata:ro
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    environment:
      - NETDATA_CLAIM_TOKEN=FnQggaW0ttKaVQVWvuow9h56m1Y1L5I2tqwh4x5ap6h9zjrLFzywR21O6VzMQubftEqLiPx-y-nvAEoEr7TBs8O7GpcGH8AnsQ8HQ7LzeRHGCOM6r_TSswZXnMh_FaSJV8CDJw4
      - NETDATA_CLAIM_URL=https://app.netdata.cloud
      - NETDATA_CLAIM_ROOMS=6dab7580-c5eb-43a0-8e5e-392e3f5e5a98

volumes:
  netdatalib:
  netdatacache:
