services:
  pihole:
    container_name: pihole
    image: ghcr.io/pi-hole/pihole
    hostname: pihole
    network_mode: "host"
    environment:
      - TZ=America/Chicago
      - FTLCONF_REPLY_ADDR4=192.168.1.1
     #- PIHOLE_DNS_=1.1.1.1;2606:4700:4700::1111;74.82.42.42;2001:470:20::2
      - PIHOLE_DNS_=1.1.1.1;2001:470:20::2
      - VIRTUAL_HOST=pihole.tacomafia.net
      - INTERFACE=lan0
      - DNSMASQ_LISTENING=local
      - WEB_PORT=8000
    volumes:
      - /opt/appdata/pihole/etc/pihole:/etc/pihole
      - /opt/appdata/pihole/etc/dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - CHOWN
    restart: unless-stopped
  cloudflare-ddns:
    image: ghcr.io/joshuaavalon/cloudflare-ddns
    container_name: cloudflare-ddns
    network_mode: "host"
    environment:
      - PUID=114
      - PGID=120
      - CRON=*/60 * * * *
    volumes:
      - /opt/appdata/cloudflare-ddns/config.yaml:/app/config.yaml
    restart: unless-stopped
  telegraf:
    image: telegraf
    container_name: telegraf
    network_mode: "host"
    environment:
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_MOUNT_PREFIX=/hostfs
    volumes:
      - /opt/appdata/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /:/hostfs:ro
      - /etc:/hostfs/etc:ro
      - /proc:/hostfs/proc:ro
      - /sys:/hostfs/sys:ro
      - /var/run/utmp:/var/run/utmp:ro
    restart: unless-stopped
