version: "3.9"
services:
  nginx:
    image: ghcr.io/kylhill/docker-nginx:nightly
    container_name: nginx
    environment:
      - TZ=America/Chicago
    volumes:
      - ./appdata/nginx/etc:/etc/nginx:ro
      - ./appdata/nginx/www:/var/www:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
  adguard:
    image: docker.io/adguard/adguardhome:latest
    container_name: adguard
    environment:
      - TZ=America/Chicago
    volumes:
      - ./appdata/adguard/work:/opt/adguardhome/work
      - ./appdata/adguard/conf:/opt/adguardhome/conf
    ports:
      - "853:853/udp"
    restart: unless-stopped
  uptime-kuma:
    image: docker.io/louislam/uptime-kuma:latest
    container_name: uptime-kuma
    environment:
      - PUID=110
      - PGID=116
    volumes:
      - ./appdata/uptime-kuma:/app/data
    restart: unless-stopped
networks:
  default:
    ipam:
      config:
        - subnet: 172.17.0.0/16
