services:
  adguard:
    image: docker.io/adguard/adguardhome:latest
    container_name: adguard
    volumes:
      - /opt/appdata/adguard/work:/opt/adguardhome/work
      - /opt/appdata/adguard/conf:/opt/adguardhome/conf
    #ports:
      #- "784:784/udp"
      #- "853:853"
    restart: unless-stopped
  uptime-kuma:
    image: docker.io/louislam/uptime-kuma:latest
    container_name: uptime-kuma
    depends_on:
      - nginx
    volumes:
      - /opt/appdata/uptime-kuma:/app/data
    restart: unless-stopped
  nginx:
    image: docker.io/ubuntu/nginx:latest
    container_name: nginx
    volumes:
      - /opt/appdata/nginx/etc/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/appdata/nginx/etc/sites-enabled:/etc/nginx/sites-enabled:ro
      - /opt/appdata/nginx/etc/snippets:/etc/nginx/snippets:ro
      - /opt/appdata/nginx/etc/conf.d:/etc/nginx/conf.d:ro
      - /opt/appdata/nginx/www:/var/www:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
  authelia:
    image: ghcr.io/authelia/authelia:latest
    container_name: authelia
    user: "111:123"
    environment:
      - TZ=America/Chicago
    volumes:
      - /opt/appdata/authelia:/config
    restart: unless-stopped
networks:
  default:
    ipam:
      config:
        - subnet: 172.17.0.0/16
