services:
  kanzi:
    image: lscr.io/linuxserver/kanzi
    container_name: kanzi
    environment:
      - PUID=119
      - PGID=123
      - TZ=America/Chicago
      - INVOCATION_NAME=kodi
      - URL_ENDPOINT=https://kanzi.tacomafia.net
    volumes:
      - /opt/appdata/kanzi:/config
    ports:
      - "127.0.0.1:8000:8000"
    restart: unless-stopped
  flexget:
    image: ghcr.io/wiserain/flexget
    container_name: flexget
    environment:
      - PUID=114
      - PGID=124
      - TZ=America/Chicago
      - FG_LOG_LEVEL=info
    volumes:
      - /opt/appdata/flexget:/config
      - /srv/shared/video/Series:/srv/shared/video/Series:ro
    restart: unless-stopped
  freshrss:
    image: lscr.io/linuxserver/freshrss
    container_name: freshrss
    environment:
      - PUID=120
      - PGID=125
      - TZ=America/Chicago
    volumes:
      - /opt/appdata/freshrss:/config
    ports:
      - "127.0.0.1:8001:80"
    restart: unless-stopped
  deluge:
    image: lscr.io/linuxserver/deluge
    container_name: deluge
    network_mode: "host"
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
      - UMASK_SET=022
      - DELUGE_LOGLEVEL=warning
    volumes:
      - /opt/appdata/deluge:/config
      - /var/working:/var/working
      - /srv/shared/torrents:/srv/shared/torrents
    restart: unless-stopped
  fulltextrss:
    image: heussd/fivefilters-full-text-rss
    container_name: fulltextrss
    volumes:
      - /var/www/html/cache
      - /opt/appdata/fulltextrss/ftr-site-config:/var/www/html/site_config/standard:ro
      - /opt/appdata/fulltextrss/custom_config.php:/var/www/html/custom_config.php:ro
      - /opt/appdata/fulltextrss/mpm_prefork.conf:/etc/apache2/mods-enabled/mpm_prefork.conf:ro
    ports:
      - "127.0.0.1:8002:80"
    restart: unless-stopped
  grocy:
    image: lscr.io/linuxserver/grocy
    container_name: grocy
    environment:
      - PUID=121
      - PGID=126
      - TZ=America/Chicago
    volumes:
      - /opt/appdata/grocy:/config
    ports:
      - "127.0.0.1:8003:80"
    restart: unless-stopped
  doh-server:
    image: satishweb/doh-server
    container_name: doh-server
    network_mode: "host"
    environment:
      DEBUG: "0"
      UPSTREAM_DNS_SERVER: "udp:192.168.1.1:53"
      DOH_HTTP_PREFIX: "/dns-query"
      DOH_SERVER_LISTEN: ":8053"
    restart: unless-stopped
  cloudflare-ddns:
    image: ghcr.io/joshuaavalon/cloudflare-ddns
    container_name: cloudflare-ddns
    network_mode: "host"
    environment:
      PUID: "117"
      PGID: "127"
      CRON: "*/60 * * * *"
    volumes:
      - /opt/appdata/cloudflare-ddns/config.yaml:/app/config.yaml
    restart: unless-stopped
#  homeassistant:
#    image: lscr.io/linuxserver/homeassistant
#    container_name: homeassistant
#    environment:
#      - PUID=123
#      - PGID=128
#      - TZ=America/Chicago
#    volumes:
#      - /opt/appdata/homeassistant:/config
#    ports:
#        - "127.0.0.1:8005:8123"
#    restart: unless-stopped
  minecraft:
    image: itzg/minecraft-bedrock-server
    container_name: minecraft
    environment:
      EULA: "TRUE"
      SERVER_NAME: "Dad's Server"
      GAMEMODE: "survival"
      DIFFICULTY: "normal"
      OPS: "2533274795625937,2535405415054487,2535405917118583"
      #ALLOW_LIST_USERS: "monkeyman 67156,IsaacChief13,OfficerCarson17"
    volumes:
      - /opt/appdata/minecraft:/data
    ports:
      - "19132:19132/udp"
    stdin_open: true
    tty: true
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: syntax.l.tacomafia.net
    ports:
      - "127.0.0.1:19999:19999"
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /opt/appdata/netdata/config:/etc/netdata:ro
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    environment:
      - NETDATA_CLAIM_TOKEN=FnQggaW0ttKaVQVWvuow9h56m1Y1L5I2tqwh4x5ap6h9zjrLFzywR21O6VzMQubftEqLiPx-y-nvAEoEr7TBs8O7GpcGH8AnsQ8HQ7LzeRHGCOM6r_TSswZXnMh_FaSJV8CDJw4
      - NETDATA_CLAIM_URL=https://app.netdata.cloud
      - NETDATA_CLAIM_ROOMS=6dab7580-c5eb-43a0-8e5e-392e3f5e5a98

volumes:
  netdatalib:
  netdatacache:
