services:
  kanzi:
    image: lscr.io/linuxserver/kanzi:latest
    container_name: kanzi
    environment:
      - PUID=119
      - PGID=123
      - TZ=America/Chicago
      - INVOCATION_NAME=kodi
      - URL_ENDPOINT=https://kanzi.tacomafia.net
    volumes:
      - /opt/appdata/kanzi:/config
    restart: unless-stopped
  flexget:
    image: ghcr.io/wiserain/flexget:latest
    container_name: flexget
    environment:
      - PUID=114
      - PGID=124
      - TZ=America/Chicago
    volumes:
      - /opt/appdata/flexget:/config
      - /srv/shared/video/Series:/srv/shared/video/Series:ro
    restart: unless-stopped
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    depends_on:
      - mariadb
      - fulltextrss
    environment:
      - PUID=120
      - PGID=125
      - TZ=America/Chicago
    volumes:
      - /opt/appdata/freshrss:/config
    restart: unless-stopped
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    network_mode: "host"
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
      - UMASK=022
    volumes:
      - /opt/appdata/deluge:/config
      - /var/working:/var/working
      - /srv/shared/torrents:/srv/shared/torrents
    restart: unless-stopped
  fulltextrss:
    image: heussd/fivefilters-full-text-rss:latest
    container_name: fulltextrss
    volumes:
      - /var/www/html/cache
      - /opt/appdata/fulltextrss/ftr-site-config:/var/www/html/site_config/standard:ro
      - /opt/appdata/fulltextrss/custom_config.php:/var/www/html/custom_config.php:ro
      - /opt/appdata/fulltextrss/mpm_prefork.conf:/etc/apache2/mods-enabled/mpm_prefork.conf:ro
    restart: unless-stopped
  grocy:
    image: lscr.io/linuxserver/grocy:latest
    container_name: grocy
    environment:
      - PUID=121
      - PGID=126
      - TZ=America/Chicago
    volumes:
      - /opt/appdata/grocy:/config
    restart: unless-stopped
  doh-server:
    image: satishweb/doh-server:latest
    container_name: doh-server
    environment:
      - UPSTREAM_DNS_SERVER=udp:192.168.1.1:53
      - DOH_HTTP_PREFIX=/dns-query
    restart: unless-stopped
  cloudflare-ddns:
    image: ghcr.io/joshuaavalon/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    network_mode: "host"
    environment:
      - PUID=117
      - PGID=127
      - CRON=*/30 * * * *
    volumes:
      - /opt/appdata/cloudflare-ddns/config.yaml:/app/config.yaml
    restart: unless-stopped
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller:latest
    container_name: unifi-controller
    environment:
      - PUID=115
      - PGID=121
      - MEM_LIMIT=512
      - MEM_STARTUP=512
    ports:
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "8080:8080"
      - "8443:8443"
    volumes:
      - /opt/appdata/unifi-controller:/config
    restart: unless-stopped
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: "host"
    environment:
      - PUID=123
      - PGID=128
      - TZ=America/Chicago
    volumes:
      - /opt/appdata/homeassistant:/config
      - /srv/shared:/srv/shared:ro
    restart: unless-stopped
  esphome:
    image: ghcr.io/esphome/esphome:latest
    container_name: esphome
    network_mode: "host"
    volumes:
      - /opt/appdata/esphome:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - /opt/appdata/uptime-kuma:/app/data
    restart: unless-stopped
  mariadb:
    image: lscr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=109
      - PGID=115
      - TZ=America/Chicago
    volumes:
      - /opt/appdata/mariadb:/config
    ports:
      - "3306:3306"
    restart: unless-stopped
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=33
      - PGID=33
      - TZ=America/Chicago
      - URL=tacomafia.net
      - VALIDATION=dns
      - SUBDOMAINS=wildcard
      - DNSPLUGIN=cloudflare
      - EMAIL= kylhill@gmail.com
      - EXTRA_DOMAINS= "*.l.tacomafia.net"
    volumes:
      - /opt/appdata/swag:/config
      - /srv/backup:/srv/backup:ro
      - /srv/kws:/srv/kws:ro
      - /srv/shared:/srv/shared:ro
    ports:
      - "443:443"
      - "80:80"
    restart: unless-stopped
#  minecraft:
#    image: itzg/minecraft-bedrock-server:latest
#    container_name: minecraft
#    environment:
#      - EULA=TRUE
#      - SERVER_NAME=Dad's Server
#      - GAMEMODE=survival
#      - DIFFICULTY=normal
#      - OPS=2533274795625937,2535405415054487,2535405917118583
#      #- ALLOW_LIST_USERS=monkeyman 67156,IsaacChief13,OfficerCarson17
#    volumes:
#      - /opt/appdata/minecraft:/data
#    ports:
#      - "19132:19132/udp"
#    stdin_open: true
#    tty: true
#    restart: unless-stopped
