templates:
  tv:
    # Lookup show metadata from TheTVDB
    thetvdb_lookup: yes

    # Try to parse additional information from file names
    parsing:
      series: guessit

    # Make sure all filenames are Windows safe
    pathscrub: windows

    # Don't download if we have less than 10 GB of free space
    free_space:
      path: /srv/shared/torrents/
      space: 10000

    # Output entities to Deluge
    deluge:
      queue_to_top: yes
      remove_at_ratio: yes

      # Rename files using TheTVDB metadata: "Series Name/Sx0E - Episode Name"
      content_filename: /{{ series_season }}x{{ series_episode|pad(2) }}{% if tvdb_ep_name %} - {{ tvdb_ep_name }}{% endif %}
      move_completed_path: /srv/shared/torrents/{{ tvdb_series_name|default(series_name) }}

tasks:
  tv-private:
    template: tv
    priority: 1

    # Private RSS feed for TV shows from morethan.tv
    rss:
      url: https://www.morethan.tv/feeds.php?feed=torrents_tv&user=29212&auth=56334d999e47d093a963b47ea822356f&passkey=ah6polqnqemxtw50i0ggnivc76e0lbic&authkey=mkhit4lab7s78t1lfu0qghxz1mhy13l7
      all_entries: no

    series:
      settings:
        shows:
          # Wait for a 720p hdtv (or better) release for 24 hours, after that
          # download the best episode seen, up to 1080p.
          timeframe: 24 hours
          target: 720p hdtv+
          quality: <=1080p webrip+

          # Download the target quality if it becomes available after the timeframe
          upgrade: yes

          # Download new season packs as they become available
          #season_packs: always

      # TV shows to download...
      shows:
        - Archer (2009)
        - Ask the StoryBots
        - Blaze and the Monster Machines
        - Bluey (2018)
        - Bull (2016)
        - Curious George
        - Dino Dana
        - Dinotrux
        - Derry Girls
        - DuckTales (2017)
        - Grey's Anatomy
        - LEGO Star Wars
        - LEGO Ninjago Masters of Spinjitzu
        - Modern Family
        - PJ Masks
        - Pete the Cat
        - Schitt's Creek
        - Star Trek Picard
        - Star Wars Resistance
        - Star Wars Clone Wars
        - The Boss Baby Back in Business
        - The Marvelous Mrs. Maisel
        - The Magic School Bus Rides Again
        - The Mandalorian
        - The Simpsons
        - This is Us
        - Tom Clancy's Jack Ryan
        - Whose Line is it Anyway? (US)
        - Wild Kratts
        - Young Sheldon

    deluge:
      ratio: 0.33

  #tv-public:
    #template: tv
    #priority: 2

    # showRSS: magnets, no namespaces, cleaned names, per-show settings for quality and propers
    #rss: https://showrss.info/user/219.rss?magnets=true&namespaces=false&name=clean&quality=null&re=null

    # Download all series from the custom feed
    #all_series: yes
    #accept_all: yes

    # Deluge settings for public torrents
    #deluge:
      #main_file_only: yes
      #hide_sparse_files: no
      #keep_subs: no
      #magnetization_timeout: 60     # wait up to 60s to allow for file renaming
      #ratio: 0
      #max_up_speed: 100.0           # don't attract too much attention

