templates:
  tv:
    # Lookup show metadata from TheTVDB
    thetvdb_lookup: yes

    # Try to parse additional information from file names
    parsing:
      series: guessit

    # Make sure all filenames are Windows safe
    pathscrub: windows

    # Output entities to Deluge
    deluge:
      queue_to_top: yes
      remove_at_ratio: yes

      # Rename files using TheTVDB metadata: "Series Name/Sx0E - Episode Name"
      content_filename: /{{ series_season }}x{{ series_episode|pad(2) }}{% if tvdb_ep_name %} - {{ tvdb_ep_name }}{% endif %}
      move_completed_path: /srv/shared/torrents/{{ tvdb_series_name|default(series_name) }}

tasks:
  tv-private:
    template: tv
    priority: 1

    # Private RSS feed for TV shows from morethan.tv
    rss:
      url: https://www.morethan.tv/feeds.php?feed=torrents_tv&user=29212&auth=56334d999e47d093a963b47ea822356f&passkey=ah6polqnqemxtw50i0ggnivc76e0lbic&authkey=mkhit4lab7s78t1lfu0qghxz1mhy13l7
      all_entries: no

    configure_series:
      from:
        # Download shows from any series that we already have
        filesystem:
          path: /srv/shared/video/Series/
          retrieve: dirs

      settings:
        # Wait for a (720p hdtv+ h264+) or (1080p hdtv+ h265+) release for 12 hours, after that download the best (720p-1080p webprip+ h264+) episode available.
        timeframe: 12 hours
        qualities:
          - 720p hdtv+ h264+
          - 1080p hdtv+ h265+
        quality: 720p-1080p webrip+ h264+

        # Download the target quality if it becomes available after the timeframe
        upgrade: yes

        # Don't download specials
        specials: no

        # Download new season packs as they become available
        #season_packs: always

    # Deluge settings for private torrents
    #deluge:
      #ratio: 0.33

    # Force strict checking to avoid downloading stuff we don't want
    series:
      - "Law & Order":
          exact: yes
      - "The War":
          exact: yes

  tv-showrss:
    template: tv
    priority: 2

    # showRSS: magnets, no namespaces, raw names, per-show settings for quality and propers
    rss:
      url: https://showrss.info/user/246806.rss?magnets=true&namespaces=false&name=null&quality=null&re=null
      all_entries: yes

    # Download all series from the custom feed
    all_series: yes
    accept_all: yes

    # Deluge settings for public torrents
    deluge:
      main_file_only: yes
      hide_sparse_files: no
      keep_subs: no
      magnetization_timeout: 60     # wait up to 60s to allow for file renaming
      ratio: 0
      max_up_speed: 100.0           # don't attract too much attention

#web_server:
  #bind: 127.0.0.1
  #base_url: /flexget

schedules:
 - tasks: [tv-private, tv-showrss]
    interval:
      hours: 1
      jitter: 300
