# Move around panes with j and k, a bit like vim
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Move between windows with Ctrl-h and Ctrl-l
bind-key -r C-h select-window -t :-
bind-key -r C-l select-window -t :+

# Resize pane shortcuts
bind -r H resize-pane -L 10
bind -r J resize-pane -D 10
bind -r K resize-pane -U 10
bind -r L resize-pane -R 10

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

# Use 256 color tmux if terminal supports it
if-shell 'test $(tput colors) -ge 256' 'set-option -g default-terminal "screen-256color"'
if-shell 'test $(tput colors) -ge 256' 'set-option -ga terminal-overrides ",*-256color:Tc"'

# Make Ctrl+Left and Ctrl+Right work properly
set -ga terminal-overrides "xterm*:kLFT5=\eOD:kRIT5=\eOC:kUP5=\eOA:kDN5=\eOB:smkx@:rmkx@"

# Update terminal window title dynamically
set-option -g set-titles on
set-option -g set-titles-string '#(whoami)@#(hostname -f)'

# Start window numbers at 1 to match keyboard order with tmux window order
set-option -g base-index 1
set-window-option -g pane-base-index 1

# Renumber windows sequentially after closing any of them
set-option -g renumber-windows on

# Don't show hardcoded byobu date/time
set-option -g status-right '#(byobu-status tmux_right)'

#############################################
# Solarized dark color scheme
#############################################

# pane border
set-option -g  pane-active-border-style bg=$BYOBU_DARK
set-option -ga pane-active-border-style fg=$BYOBU_HIGHLIGHT
set-option -g  pane-border-style fg=$BYOBU_ACCENT
set-option -ga pane-border-style bg=$BYOBU_DARK

# window mode
set-option -g  mode-style bg=$BYOBU_DARK
set-option -ga mode-style fg=$BYOBU_LIGHT

# default window title colors
set-window-option -g  window-status-style bg=$BYOBU_DARK
set-window-option -ga window-status-style fg=$BYOBU_LIGHT

# active window title colors
set-window-option -g  window-status-current-style bg=$BYOBU_HIGHLIGHT
set-window-option -ga window-status-current-style fg=$BYOBU_BRIGHT

# window activity colors
set-window-option -g  window-status-activity-style bg=$BYOBU_DARK
set-window-option -ga window-status-activity-style fg=$BYOBU_LIGHT

# default status bar colors
set-option -g  status-style bg=$BYOBU_DARK
set-option -ga status-style fg=$BYOBU_LIGHT

# message text
set-option -g  message-style bg=$BYOBU_DARK
set-option -ga message-style fg=$BYOBU_LIGHT

