# Pass aliases through sudo - https://wiki.archlinux.org/title/Sudo#P
alias sudo='sudo '

# Handy docker aliases - https://docs.linuxserver.io/general/docker-compose
alias dtail='docker logs -tf --tail="50" "$@"'
alias dprune='docker system prune -a -f --volumes'

alias bashreload='source ~/.bashrc && echo Bash config reloaded;'

# Easy borgmatic unmount
alias bumount='borgmatic umount --mount-point /media/borg'
